### ISSUE TITLE
YT-rss can't get all links

### ISSUE THREAD

**Issue by geirawsm** [geirawsm/sausage_bot#21]
`Youtube.get_videos_from_yt_link()` can only get YT-links that have feeds available:

By username: `https://www.youtube.com/feeds/videos.xml?user=[ID]`
By channel ID: `https://www.youtube.com/feeds/videos.xml?channel_id=[ID]`

But links like `https://www.youtube.com/c/DAVIDLYNCHTHEATER` doesn't work this way.

The ID has to be fetched specifically.

**Comment by glennlunder** [comment]
I see there is an example above, but it's not exactly always like that, since: 

`https://www.youtube.com/c/hellcatrecords/`  - works
`https://www.youtube.com/c/unfdcentral/` - doesn't

So the formatting of the name is not the cause of the issue, and I have yet to find a difference between the two channels looking at the web at least.

**Comment by geirawsm** [comment]
175827e4ee5ab1b89b0cb8c5b2f3de8e077c5b0f
